### ISSUE TITLE
Not working with Angular 9.0.7

### ISSUE THREAD

**Issue by jlweb58** [nishantmc/angular-material-fileupload#70]
While compiling I get the following error:
ERROR in Failed to compile entry-point angular-material-fileupload (es2015 as esm2015) due to compilation errors:
node_modules/angular-material-fileupload/fesm2015/angular-material-fileupload.js:596:26 - error NG1010: Value at position 0 in the NgModule.imports of MatFileUploadModule is not a reference: [object Object]

596                 imports: [
                             ~
597                     MatProgressBarModule,
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
... 
602                     CommonModule,
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
603                 ],
    ~~~~~~~~~~~~~~~~~


My version info:
Angular CLI: 9.0.7
Node: 10.19.0
OS: linux x64

Angular: 9.0.7
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.7
@angular-devkit/build-angular     0.900.7
@angular-devkit/build-optimizer   0.900.7
@angular-devkit/build-webpack     0.900.7
@angular-devkit/core              9.0.7
@angular-devkit/schematics        9.0.7
@angular/cdk                      9.2.3
@angular/flex-layout              9.0.0-beta.29
@angular/google-maps              10.2.7
@angular/material                 9.2.3
@ngtools/webpack                  9.0.7
@schematics/angular               9.0.7
@schematics/update                0.900.7
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2

**Comment by cyrilmarois** [comment]
I got the sane with angular 10

"@angular/animations": "~10.2.3",
    "@angular/cdk": "~10.2.7",
    "@angular/common": "~10.2.3",
    "@angular/compiler": "~10.2.3",
    "@angular/core": "~10.2.3",
    "@angular/forms": "~10.2.3",
    "@angular/material": "^10.2.7",
    "@angular/platform-browser": "~10.2.3",
    "@angular/platform-browser-dynamic": "~10.2.3",
    "@angular/router": "~10.2.3",
    "@ng-bootstrap/ng-bootstrap": "^8.0.0",
    "angular-material-fileupload": "^3.0.1",
    "bootstrap": "^4.4.1",
    "material-components-web": "^4.0.0",
    "rxjs": "~6.6.3",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.2"
