### ISSUE TITLE
does this work with angular 5.2.0

### ISSUE THREAD

**Issue by isandeeppatil** [nishantmc/angular-material-fileupload#34]
Does this work with angular 5.2.0 ? when I am trying to install in my project and try to use it i get foloowing error - 

ERROR in node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
node_modules/angular-material-fileupload/node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.

**Comment by andregufc** [comment]
I have the same issue with Angular 7

**Comment by matcho** [comment]
Same error with angular 7:
`node_modules/angular-material-fileupload/node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.`

**Comment by duard** [comment]
Same error here ... latest angular +7

**Comment by nishantmc** [comment]
The latest version 2.0.0 has fixes for angular 7 and supports "aot". Can you try this version?

**Comment by maxma1411** [comment]
Version 2.0.0 and Angular 7:
ERROR in angular-material-fileupload\matFileUpload.module.ts(13,2): Error during template compile of 'MatFileUploadModule'  Function calls are not supported in decorators but 'ɵmakeDecorator' was called in 'NgModule'
    'NgModule' calls 'ɵmakeDecorator'.
node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
node_modules/angular-material-fileupload/node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.

**Comment by nishantmc** [comment]
@maxma1411 How are you building the app? can you post the deps in package.json?

**Comment by maxma1411** [comment]
I have the error building with "ng build --prod" or starting the app with "ng serve" 
my package.json:
{
  "name": "gea",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular-devkit/core": "^7.3.1",
    "@angular/animations": "^7.2.2",
    "@angular/cdk": "^7.2.1",
    "@angular/common": "^7.0.4",
    "@angular/compiler": "^7.0.4",
    "@angular/core": "^7.0.4",
    "@angular/forms": "^7.0.4",
    "@angular/http": "^7.0.4",
    "@angular/material": "^7.2.1",
    "@angular/platform-browser": "^7.0.4",
    "@angular/platform-browser-dynamic": "^7.0.4",
    "@angular/router": "^7.0.4",
    "@auth0/angular-jwt": "^2.0.0",
    "@ngx-translate/core": "^11.0.1",
    "@ngx-translate/http-loader": "^4.0.0",
    "@swimlane/ngx-datatable": "^14.0.0",
    "angular-material-fileupload": "^2.0.0",
    "angular-tslint-rules": "^1.12.1",
    "core-js": "^2.5.4",
    "hammerjs": "^2.0.8",
    "jwt-decode": "^2.2.0",
    "rxjs": "~6.3.3",
    "zone.js": "~0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.12.0",
    "@angular/cli": "^7.0.7",
    "@angular/compiler-cli": "^7.0.4",
    "@angular/language-service": "^7.0.4",
    "@types/jasmine": "^2.8.12",
    "@types/jasminewd2": "^2.0.6",
    "@types/jquery": "^3.3.22",
    "@types/jwt-decode": "^2.2.1",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.5.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "^3.1.6"
  }
}

**Comment by nishantmc** [comment]
@maxma1411 Can you post your tsconfig file?

**Comment by maxma1411** [comment]
@nishantmc, tsconfig.json

**Comment by nishantmc** [comment]
Couldn't replicate the issue. Tried
* ng new angular-cli-test18
* changed deps and devdeps to what you mentioned above
* imported angular-material-fileupload and used the component in html
ng serve --prod works without any issues, You can try these steps

Not sure whether you are hitting his issue https://github.com/angular/angular/issues/23609

**Comment by nishantmc** [comment]
Please refer #35
