### ISSUE TITLE
Not working in Angular 10.1.4

### ISSUE THREAD

**Issue by jacques-hoventer** [nishantmc/angular-material-fileupload#66]
I tried using it in an Angular 10.1.4 application - getting the following error when I build or try to run and watch the app: 

ERROR in Failed to compile entry-point angular-material-fileupload (es2015 as esm2015) due to compilation errors:
node_modules/angular-material-fileupload/fesm2015/angular-material-fileupload.js:596:26 - error NG1010: Value at position 0 in the NgModule.imports of MatFileUploadModule is not a reference
  Value could not be determined statically.

596                 imports: [
                             ~
597                     MatProgressBarModule,
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
...
602                     CommonModule,
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
603                 ],
    ~~~~~~~~~~~~~~~~~

  node_modules/angular-material-fileupload/fesm2015/angular-material-fileupload.js:597:21
    597                     MatProgressBarModule,
                            ~~~~~~~~~~~~~~~~~~~~
    Unknown reference.

**Comment by jacques-hoventer** [comment]
PS. I have Angular Material installed

**Comment by dobromyslov** [comment]
Yep. Having the same error.

**Comment by RoySijnesael** [comment]
Same!

**Comment by kampytaru** [comment]
This is happening because Angular Material 10 no longer allows barrel imports for its modules.  I opened a PR to fix this problem but in the mean time, you can replace the module imports in fesm2015/angular-material-fileupload.js with:

`import { MatIconModule } from '@angular/material/icon';
import { MatProgressBarModule } from '@angular/material/progress-bar';
import { MatCardModule } from '@angular/material/card';
import { MatButtonModule } from '@angular/material/button';`

**Comment by jlweb58** [comment]
Same problem with Angular 9.0.7

**Comment by arnaudprioul** [comment]
Hi,
I have same problem and it work (for local developpement) with :
 
> `import { MatIconModule } from '@angular/material/icon'; import { MatProgressBarModule } from '@angular/material/progress-bar'; import { MatCardModule } from '@angular/material/card'; import { MatButtonModule } from '@angular/material/button';`

I hope your PR will be validate soon.
